name: matshochine
description: A world-class AI powered fish species identification app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  glassmorphism: ^3.0.0
  
  # ML & Camera
  tflite_flutter: ^0.10.4
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  
  # Data & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # AI & API
  google_generative_ai: ^0.4.0
  http: ^1.2.0
  
  # Utilities
  equatable: ^2.0.5
  intl: ^0.19.0
  sqflite_common_ffi_web: ^1.0.2

  cross_file: any
  flutter_tts: ^4.2.5
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^19.5.0
  timezone: any
  connectivity_plus: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
